# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    bucket      = "poc-development-terraform-state"
    credentials = "/Users/dayronremigio/devops/terraform/poc-terraform-terragrunt-gcp-gke/poc-project/dev/credentials.json"
    prefix      = "dev/gcp-gke"
  }
}
