# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "google" {
  project     = "locate-me-device"
  region      = "us-east1"
}
provider "google-beta" {
  project     = "locate-me-device"
  region      = "us-east1"
}
